// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vklghnfhqguzrtwinarv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbGdobmZocWd1enJ0d2luYXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTk2NjAsImV4cCI6MjA2OTczNTY2MH0.ThyfJo50CDupWSmlT9cebYcYbW8ySmprTQ4ClJLoFck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});